import { describe, expect, it } from "vitest";
import { canAccess, classifyLearnRoute, requiredRole, type AppUser } from "../../src/auth/authorization";

const admin: AppUser = { id: "a", email: "admin@example.com", display_name: "Admin", role: "ADMIN", status: "ACTIVE" };
const student: AppUser = { id: "s", email: "student@example.com", display_name: "Student", role: "STUDENT", status: "ACTIVE" };

describe("Learn route authorization", () => {
  it("classifies direct routes", () => {
    expect(classifyLearnRoute("/learn")).toBe("entry");
    expect(classifyLearnRoute("/learn/admin")).toBe("admin");
    expect(classifyLearnRoute("/learn/admin/calendar")).toBe("admin-calendar");
    expect(classifyLearnRoute("/learn/admin/bookings")).toBe("admin-bookings");
    expect(classifyLearnRoute("/learn/admin/resources")).toBe("admin-resources");
    expect(classifyLearnRoute("/learn/admin/resources/new")).toBe("admin-resource-form");
    expect(classifyLearnRoute("/learn/admin/resources/resource-1/download")).toBe("admin-resource-download");
    expect(classifyLearnRoute("/learn/admin/resources/bulk-delete")).toBe("admin-resource-bulk-delete");
    expect(classifyLearnRoute("/learn/student/lessons")).toBe("student");
    expect(classifyLearnRoute("/learn/student/resources")).toBe("student-resources");
    expect(classifyLearnRoute("/learn/student/resources/resource-1/download")).toBe("student-resource-download");
    expect(classifyLearnRoute("/learn/student/calendar")).toBe("student-calendar");
    expect(classifyLearnRoute("/learn/admin/calendar/feed")).toBe("admin-calendar-feed");
    expect(classifyLearnRoute("/learn/student/calendar/feed")).toBe("student-calendar-feed");
    expect(classifyLearnRoute("/learn/admin/students/new")).toBe("admin-student-form");
    expect(classifyLearnRoute("/learn/admin/lessons/lesson-1/status")).toBe("admin-lesson-status");
    expect(classifyLearnRoute("/learn/admin/lessons/lesson-1/report")).toBe("admin-lesson-report");
    expect(classifyLearnRoute("/learn/admin/lessons/lesson-1/report.pdf")).toBe("admin-lesson-report-pdf");
    expect(classifyLearnRoute("/learn/admin/notifications")).toBe("admin-notifications");
    expect(classifyLearnRoute("/learn/admin/notifications/settings")).toBe("admin-notifications");
    expect(classifyLearnRoute("/learn/admin/notifications/preview/LESSON_CREATED")).toBe("admin-notifications");
    expect(classifyLearnRoute("/learn/admin/notifications/notification-1/preview")).toBe("admin-notification");
    expect(classifyLearnRoute("/learn/admin/notifications/notification-1")).toBe("admin-notification");
    expect(classifyLearnRoute("/learn/admin/accounting")).toBe("admin-accounting");
    expect(classifyLearnRoute("/learn/admin/accounting/contacts/student-1")).toBe("admin-accounting-contact");
    expect(classifyLearnRoute("/learn/admin/accounting/contacts/student-1/remove")).toBe("admin-accounting-contact");
    expect(classifyLearnRoute("/learn/admin/accounting/event-1/retry")).toBe("admin-accounting-retry");
    expect(classifyLearnRoute("/learn/admin/accounting/event-1/reconcile")).toBe("admin-accounting-reconcile");
    expect(classifyLearnRoute("/learn/admin/accounting/connect")).toBe("admin-accounting-connect");
    expect(classifyLearnRoute("/learn/admin/accounting/oauth/callback")).toBe("admin-accounting-callback");
    expect(classifyLearnRoute("/learn/admin/reschedules")).toBe("admin-reschedules");
    expect(classifyLearnRoute("/learn/admin/reschedules/request-1/approve")).toBe("admin-reschedule-approve");
    expect(classifyLearnRoute("/learn/admin/lessons/lesson-1/reschedule")).toBe("admin-lesson-reschedule");
    expect(classifyLearnRoute("/learn/student/lessons/lesson-1")).toBe("student-lesson");
    expect(classifyLearnRoute("/learn/student/lessons/lesson-1/cancel")).toBe("student-lesson-cancel");
    expect(classifyLearnRoute("/learn/student/lessons/lesson-1/undo-cancellation")).toBe("student-lesson-undo-cancellation");
    expect(classifyLearnRoute("/learn/student/lessons/lesson-1/reschedule")).toBe("student-lesson-reschedule");
    expect(classifyLearnRoute("/learn/student/lessons/lesson-1/report")).toBe("student-lesson-report");
    expect(classifyLearnRoute("/learn/student/lessons/lesson-1/report.pdf")).toBe("student-lesson-report-pdf");
    expect(classifyLearnRoute("/learn/terms")).toBe("legal-terms");
    expect(classifyLearnRoute("/learn/privacy")).toBe("legal-privacy");
    expect(classifyLearnRoute("/learn/assets/learn.css")).toBe("asset");
    expect(classifyLearnRoute("/learn/assets/learn_logo-240.webp")).toBe("asset");
    expect(classifyLearnRoute("/learn/assets/foxlearninglogo-240.webp")).toBe("asset");
    expect(classifyLearnRoute("/learn/assets/fonts/geist-latin-wght-normal.woff2")).toBe("asset");
    expect(classifyLearnRoute("/learn/assets/my-favicon/site.webmanifest")).toBe("asset");
    expect(classifyLearnRoute("/learn/nope")).toBe("not-found");
    expect(classifyLearnRoute("/learn.css")).toBe("not-found");
  });
  it("enforces role boundaries", () => {
    expect(canAccess(admin, "admin")).toBe(true);
    expect(canAccess(admin, "admin-bookings")).toBe(true);
    expect(canAccess(admin, "admin-resources")).toBe(true);
    expect(canAccess(admin, "student")).toBe(false);
    expect(canAccess(student, "admin-bookings")).toBe(false);
    expect(canAccess(student, "admin-resources")).toBe(false);
    expect(canAccess(student, "admin-accounting")).toBe(false);
    expect(canAccess(student, "admin-accounting-contact")).toBe(false);
    expect(canAccess(student, "student")).toBe(true);
    expect(canAccess(student, "admin")).toBe(false);
    expect(requiredRole("admin")).toBe("ADMIN");
  });
  it("allows both authenticated roles to view legal pages", () => {
    expect(requiredRole("legal-terms")).toBeNull();
    expect(requiredRole("legal-privacy")).toBeNull();
    expect(canAccess(admin, "legal-terms")).toBe(true);
    expect(canAccess(student, "legal-privacy")).toBe(true);
  });
});
